-- Target Schema Reference
create table if not exists public.target_origins (
    id bigint generated by default as identity primary key,
    code varchar(255) not null,
    name varchar(255) not null,
    target_url varchar(255) not null,
    scraper_type varchar(50) not null,
    scrap_interval integer not null,
    board varchar(50) not null,
    major varchar(255),
    last_scraped_at timestamp
);

INSERT INTO public.target_origins (id, name, target_url, scraper_type, scrap_interval, board, major, last_scraped_at, code) VALUES (1, '일반', 'https://www.uos.ac.kr/korNotice/list.do?list_id=FA1&menuid=2000005009002000000&identified=anonymous', 'COMMON', 5, 'GENERAL', null, null, 'uos.main.fa1');
INSERT INTO public.target_origins (id, name, target_url, scraper_type, scrap_interval, board, major, last_scraped_at, code) VALUES (2, '학사', 'https://www.uos.ac.kr/korNotice/list.do?list_id=FA2&menuid=2000005009003000000&identified=anonymous&', 'COMMON', 5, 'ACADEMIC', null, null, 'uos.main.fa2');
INSERT INTO public.target_origins (id, name, target_url, scraper_type, scrap_interval, board, major, last_scraped_at, code) VALUES (3, '채용', 'https://www.uos.ac.kr/korNotice/list.do?list_id=FA34&menuid=2000005009004000000&identified=anonymous', 'COMMON', 5, 'RECRUIT', null, null, 'uos.main.fa34');
INSERT INTO public.target_origins (id, name, target_url, scraper_type, scrap_interval, board, major, last_scraped_at, code) VALUES (4, '창업', 'https://www.uos.ac.kr/korColumn/list.do?list_id=FA35&menuid=2000005009005000000&identified=anonymous', 'COMMON', 5, 'ETC', null, null, 'uos.main.fa35');
INSERT INTO public.target_origins (id, name, target_url, scraper_type, scrap_interval, board, major, last_scraped_at, code) VALUES (5, '장학', 'https://scholarship.uos.ac.kr/scholarship/notice/notice/list.do?brdBbsseq=1&identified=anonymous', 'SCHOLAR', 5, 'SCHOLARSHIP', null, null, 'uos.main.scholarship');

create table if not exists public.announcement (
    id bigint generated by default as identity primary key,
    announcementdetail_id bigint unique,
    title varchar(255) not null,
    author varchar(255) not null,
    board varchar(255) not null, -- Enum: GENERAL, ACADEMIC, RECRUIT, SCHOLARSHIP, DEPARTMENT, ETC
    written_at date,
    view_count bigint not null default 0,
    created_at timestamp not null default now(),
    modified_at timestamp not null default now(),
    target_url varchar(255) not null,
    scraping_key varchar(255) unique,
    major varchar(255)
);

create table if not exists public.announcement_detail (
    id bigint generated by default as identity primary key,
    url varchar(255) not null,
    html text not null
);
